/**
 * ADAPT SQL Builder Golden-File Tests
 *
 * Safety net for Phase 3.6 SQL modifications. These tests snapshot the exact SQL
 * strings and parameter structures generated by the ADAPT SQL builders so that
 * any change to the SQL is detected immediately.
 *
 * What is validated:
 * - SQL string stability (snapshot)
 * - Parameter placeholder counts match expected parameter counts
 * - All test_run_ids appear in the generated parameter list
 * - SQL is well-formed (basic structural checks)
 * - Both AdaptResultsSQLBuilder and TrackedResultsSQLBuilder
 * - Conclusion SQL builder
 */

import { describe, it, expect } from 'vitest';
import { AdaptResultsSQLBuilder } from '../../pipelines/helpers/adapt/results/sql-builder.js';
import { TrackedResultsSQLBuilder } from '../../pipelines/helpers/adapt/results/tracked-results-sql-builder.js';
import fixtures from './adapt-fixtures.json';

describe('ADAPT SQL Builder Golden-File Tests', () => {
  const testRunIds = fixtures.testRunIds;

  describe('AdaptResultsSQLBuilder', () => {
    const builder = new AdaptResultsSQLBuilder();

    describe('buildAdaptResultsSQL', () => {
      const placeholders = testRunIds.map((_, i) => `$${i + 1}`).join(', ');
      const filterSQL = '';
      const testRunIdsCount = testRunIds.length;

      const sql = builder.buildAdaptResultsSQL(placeholders, filterSQL, testRunIdsCount);

      it('should generate stable SQL (snapshot)', () => {
        expect(sql).toMatchSnapshot();
      });

      it('should contain all expected CTEs', () => {
        expect(sql).toContain('test_metrics AS');
        expect(sql).toContain('with_control AS');
        expect(sql).toContain('with_compare_config AS');
        expect(sql).toContain('with_dynamic_statistics AS');
        expect(sql).toContain('with_threshold_calculations AS');
        expect(sql).toContain('final_results AS');
      });

      it('should contain INSERT INTO ds_adapt_results', () => {
        expect(sql).toContain('INSERT INTO ds_adapt_results');
      });

      it('should contain ON CONFLICT upsert clause', () => {
        expect(sql).toContain('ON CONFLICT (test_run_id, control_group_id, application_dashboard_id, panel_id, metric_name)');
        expect(sql).toContain('DO UPDATE SET');
      });

      it('should contain correct test run placeholders in WHERE clause', () => {
        // The WHERE clause should contain: WHERE ms.test_run_id IN ($1, $2)
        expect(sql).toContain(`ms.test_run_id IN (${placeholders})`);
      });

      it('should reference the default config parameter at correct index', () => {
        // Default config param is at testRunIdsCount + 1 = 3
        const expectedParamRef = `$${testRunIdsCount + 1}::jsonb`;
        expect(sql).toContain(expectedParamRef);
      });

      it('should have placeholder indices that do not exceed parameter count', () => {
        // Extract all $N placeholders from the SQL
        const placeholderMatches = sql.match(/\$(\d+)/g) || [];
        const indices = placeholderMatches.map((p) => parseInt(p.replace('$', ''), 10));
        const maxIndex = Math.max(...indices);

        // Max index should be testRunIdsCount + 1 (for the default config param)
        expect(maxIndex).toBe(testRunIdsCount + 1);
      });

      it('should contain all aggregation options in dynamic statistics', () => {
        const requiredAggregations = ['mean', 'median', 'min', 'max', 'last', 'q10', 'q25', 'q75', 'q90', 'q95', 'q99'];
        for (const agg of requiredAggregations) {
          expect(sql).toContain(`WHEN '${agg}' THEN`);
        }
      });

      it('should contain both p-notation and q-notation for percentiles', () => {
        const pNotations = ['p10', 'p25', 'p75', 'p90', 'p95', 'p99'];
        for (const p of pNotations) {
          expect(sql).toContain(`WHEN '${p}' THEN`);
        }
      });

      it('should contain conclusion label logic with all expected labels', () => {
        const expectedLabels = [
          "'incomparable'",
          "'ignored'",
          "'increase'",
          "'decrease'",
          "'improvement'",
          "'regression'",
          "'partial increase'",
          "'partial decrease'",
          "'partial improvement'",
          "'partial regression'",
          "'no difference'",
        ];
        for (const label of expectedLabels) {
          expect(sql).toContain(label);
        }
      });

      it('should contain threshold check types (pct, iqr, abs)', () => {
        expect(sql).toContain("'pct'");
        expect(sql).toContain("'iqr'");
        expect(sql).toContain("'abs'");
      });

      it('should contain higherIsBetter classification logic', () => {
        expect(sql).toContain("'higherIsBetter'");
      });
    });

    describe('buildAdaptResultsSQL with filter', () => {
      const placeholders = testRunIds.map((_, i) => `$${i + 1}`).join(', ');
      const filterSQL = `AND ms.application_dashboard_id = $${testRunIds.length + 2} AND ms.panel_id = $${testRunIds.length + 3}`;
      const testRunIdsCount = testRunIds.length;

      const sql = builder.buildAdaptResultsSQL(placeholders, filterSQL, testRunIdsCount);

      it('should include filter SQL in test_metrics CTE', () => {
        expect(sql).toContain(filterSQL);
      });

      it('should generate stable SQL with filter (snapshot)', () => {
        expect(sql).toMatchSnapshot();
      });
    });

    describe('buildConclusionSQL', () => {
      const placeholders = testRunIds.map((_, i) => `$${i + 1}`).join(', ');

      const sql = builder.buildConclusionSQL(placeholders);

      it('should generate stable SQL (snapshot)', () => {
        expect(sql).toMatchSnapshot();
      });

      it('should contain adapt_results_categorized CTE', () => {
        expect(sql).toContain('adapt_results_categorized AS');
      });

      it('should contain with_tracked_results CTE', () => {
        expect(sql).toContain('with_tracked_results AS');
      });

      it('should contain INSERT INTO ds_adapt_conclusion', () => {
        expect(sql).toContain('INSERT INTO ds_adapt_conclusion');
      });

      it('should contain correct test run placeholders', () => {
        expect(sql).toContain(`test_run_id IN (${placeholders})`);
      });

      it('should contain overall conclusion logic (SKIPPED, REGRESSION, PASSED)', () => {
        expect(sql).toContain("'SKIPPED'");
        expect(sql).toContain("'REGRESSION'");
        expect(sql).toContain("'PASSED'");
      });

      it('should aggregate result categories', () => {
        expect(sql).toContain('regressions');
        expect(sql).toContain('improvements');
        expect(sql).toContain('differences');
        expect(sql).toContain('no_differences');
        expect(sql).toContain('incomparable');
      });

      it('should contain details JSONB with count fields', () => {
        expect(sql).toContain("'totalResults'");
        expect(sql).toContain("'regressionCount'");
        expect(sql).toContain("'improvementCount'");
        expect(sql).toContain("'differenceCount'");
        expect(sql).toContain("'noDifferenceCount'");
        expect(sql).toContain("'incomparableCount'");
        expect(sql).toContain("'trackedRegressionCount'");
      });

      it('should have ON CONFLICT on test_run_id', () => {
        expect(sql).toContain('ON CONFLICT (test_run_id)');
      });
    });
  });

  describe('TrackedResultsSQLBuilder', () => {
    const builder = new TrackedResultsSQLBuilder();

    describe('buildTrackedResultsSQL', () => {
      const placeholders = testRunIds.map((_, i) => `$${i + 1}`).join(', ');
      const testRunIdsCount = testRunIds.length;

      const sql = builder.buildTrackedResultsSQL(placeholders, testRunIdsCount);

      it('should generate stable SQL (snapshot)', () => {
        expect(sql).toMatchSnapshot();
      });

      it('should contain all expected CTEs', () => {
        expect(sql).toContain('control_group_test_runs AS');
        expect(sql).toContain('filtered_tracked_test_runs AS');
        expect(sql).toContain('historical_regressions AS');
        expect(sql).toContain('current_metrics AS');
        expect(sql).toContain('with_control AS');
        expect(sql).toContain('with_compare_config AS');
        expect(sql).toContain('with_dynamic_statistics AS');
        expect(sql).toContain('with_threshold_calculations AS');
        expect(sql).toContain('final_tracked_results AS');
      });

      it('should contain INSERT INTO ds_adapt_tracked_results', () => {
        expect(sql).toContain('INSERT INTO ds_adapt_tracked_results');
      });

      it('should contain correct placeholders in WHERE clause', () => {
        expect(sql).toContain(`control_group_id IN (${placeholders})`);
      });

      it('should reference the default config parameter at correct index', () => {
        const expectedParamRef = `$${testRunIdsCount + 1}::jsonb`;
        expect(sql).toContain(expectedParamRef);
      });

      it('should have placeholder indices that do not exceed parameter count', () => {
        const placeholderMatches = sql.match(/\$(\d+)/g) || [];
        const indices = placeholderMatches.map((p) => parseInt(p.replace('$', ''), 10));
        const maxIndex = Math.max(...indices);

        expect(maxIndex).toBe(testRunIdsCount + 1);
      });

      it('should use temp_tracked_config_cache table', () => {
        expect(sql).toContain('temp_tracked_config_cache');
      });

      it('should reference historical control group', () => {
        expect(sql).toContain('historical_control_group_id');
      });

      it('should filter out ACCEPTED and DEBUG test runs', () => {
        expect(sql).toContain("'ACCEPTED'");
        expect(sql).toContain("'DEBUG'");
      });

      it('should contain ON CONFLICT with tracked_test_run_id', () => {
        expect(sql).toContain('ON CONFLICT (test_run_id, application_dashboard_id, panel_id, metric_name, tracked_test_run_id)');
      });

      it('should contain conclusion label logic for tracked results', () => {
        const expectedLabels = [
          "'incomparable'",
          "'ignored'",
          "'increase'",
          "'decrease'",
          "'improvement'",
          "'regression'",
          "'no difference'",
        ];
        for (const label of expectedLabels) {
          expect(sql).toContain(label);
        }
      });
    });
  });

  describe('Parameter binding validation', () => {
    it('should produce consistent SQL for the same inputs (deterministic)', () => {
      const builder = new AdaptResultsSQLBuilder();
      const placeholders = '$1, $2';
      const sql1 = builder.buildAdaptResultsSQL(placeholders, '', 2);
      const sql2 = builder.buildAdaptResultsSQL(placeholders, '', 2);
      expect(sql1).toBe(sql2);
    });

    it('should adjust default config param index based on testRunIdsCount', () => {
      const builder = new AdaptResultsSQLBuilder();

      const sql3 = builder.buildAdaptResultsSQL('$1, $2, $3', '', 3);
      expect(sql3).toContain('$4::jsonb');
      expect(sql3).not.toContain('$3::jsonb');

      const sql5 = builder.buildAdaptResultsSQL('$1, $2, $3, $4, $5', '', 5);
      expect(sql5).toContain('$6::jsonb');
      expect(sql5).not.toContain('$5::jsonb');
    });

    it('should handle single test run ID', () => {
      const builder = new AdaptResultsSQLBuilder();
      const sql = builder.buildAdaptResultsSQL('$1', '', 1);
      expect(sql).toContain('$2::jsonb');
      expect(sql).toContain('ms.test_run_id IN ($1)');
    });

    it('TrackedResultsSQLBuilder should also adjust default config param index', () => {
      const builder = new TrackedResultsSQLBuilder();

      const sql3 = builder.buildTrackedResultsSQL('$1, $2, $3', 3);
      expect(sql3).toContain('$4::jsonb');

      const sql1 = builder.buildTrackedResultsSQL('$1', 1);
      expect(sql1).toContain('$2::jsonb');
    });
  });

  describe('Fixture data validation', () => {
    it('should have all required metric scenarios in fixtures', () => {
      expect(fixtures.metrics.regression).toBeDefined();
      expect(fixtures.metrics.improvement).toBeDefined();
      expect(fixtures.metrics.noDifference).toBeDefined();
      expect(fixtures.metrics.incomparable).toBeDefined();
    });

    it('regression metric: test median should exceed control by >15%', () => {
      const { test, control } = fixtures.metrics.regression;
      const pctDiff = (test.median - control.median) / control.median;
      expect(pctDiff).toBeGreaterThan(0.15);
    });

    it('improvement metric: test median should exceed control by >15% (higherIsBetter=true)', () => {
      const { test, control, compareConfig } = fixtures.metrics.improvement;
      const pctDiff = (test.median - control.median) / control.median;
      expect(pctDiff).toBeGreaterThan(0.15);
      expect(compareConfig.metricClassification.higherIsBetter).toBe(true);
    });

    it('noDifference metric: test median should be within 15% of control', () => {
      const { test, control } = fixtures.metrics.noDifference;
      const pctDiff = Math.abs(test.median - control.median) / control.median;
      expect(pctDiff).toBeLessThan(0.15);
    });

    it('incomparable metric: should have null control data', () => {
      expect(fixtures.metrics.incomparable.control).toBeNull();
    });

    it('regression metric should have higherIsBetter=false (lower is better)', () => {
      expect(fixtures.metrics.regression.compareConfig.metricClassification.higherIsBetter).toBe(false);
    });

    it('incomparable metric should have higherIsBetter=null', () => {
      expect(fixtures.metrics.incomparable.compareConfig.metricClassification.higherIsBetter).toBeNull();
    });

    it('should have two distinct application dashboard IDs', () => {
      const dashIds = new Set([
        fixtures.metrics.regression.applicationDashboardId,
        fixtures.metrics.improvement.applicationDashboardId,
        fixtures.metrics.noDifference.applicationDashboardId,
        fixtures.metrics.incomparable.applicationDashboardId,
      ]);
      expect(dashIds.size).toBe(2);
    });

    it('default compare config should match expected structure', () => {
      const dc = fixtures.defaultCompareConfig;
      expect(dc.thresholds.aggregation).toBe('median');
      expect(dc.thresholds.percentageThreshold).toBe(0.15);
      expect(dc.thresholds.iqrThreshold).toBe(2);
      expect(dc.metricClassification.classification).toBe('unclassified');
      expect(dc.metricClassification.higherIsBetter).toBeNull();
      expect(dc.ignore).toBe(false);
      expect(dc.source).toBe('default');
    });
  });
});
