#!/usr/bin/env node
/**
 * Container Startup Script for Perfana Web
 *
 * This script:
 * 1. Generates __env.js with runtime environment variables
 * 2. Patches CSP headers in routes-manifest.json with runtime values
 * 3. Starts the Next.js production server
 *
 * This allows a single Docker image to be deployed to multiple environments
 * by setting environment variables at runtime instead of build time.
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

// Environment variable keys to expose to the client.
// Keep in sync with RUNTIME_ENV_KEYS in lib/runtime-config.ts (this is a
// standalone entrypoint that can't import the TS module).
const RUNTIME_ENV_KEYS = [
  'NEXT_PUBLIC_API_URL',
  'NEXT_PUBLIC_KEYCLOAK_URL',
  'NEXT_PUBLIC_KEYCLOAK_REALM',
  'NEXT_PUBLIC_KEYCLOAK_CLIENT_ID',
  'NEXT_PUBLIC_USE_KEYCLOAK_AUTH',
  'NEXT_PUBLIC_LOG_VIEWER_ENABLED',
  'NEXT_PUBLIC_SUT_TRANSFER_ENABLED',
];

/**
 * Generate the __env.js file with runtime environment variables
 */
function generateEnvFile() {
  const config = {};

  for (const key of RUNTIME_ENV_KEYS) {
    const value = process.env[key];
    if (value) {
      config[key] = value;
    }
  }

  const script = `// Runtime environment configuration - Generated at container startup
// Do not edit this file manually - it will be overwritten on restart
window.__ENV__ = ${JSON.stringify(config, null, 2)};
`;

  // Determine the public directory path
  // In standalone mode: /app/apps/web/.next/standalone/apps/web/public
  // In normal mode: /app/apps/web/public
  const possiblePaths = [
    path.join(process.cwd(), 'public', '__env.js'),
    path.join(process.cwd(), '.next', 'standalone', 'apps', 'web', 'public', '__env.js'),
    path.join(process.cwd(), '..', '..', 'public', '__env.js'),
  ];

  let written = false;
  for (const envPath of possiblePaths) {
    try {
      // Ensure directory exists
      const dir = path.dirname(envPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(envPath, script, 'utf8');
      console.log(`[env-config] Generated ${envPath}`);
      console.log(`[env-config] Environment variables: ${Object.keys(config).join(', ') || 'none'}`);
      written = true;
    } catch {
      // Try next path
    }
  }

  if (!written) {
    console.warn('[env-config] Warning: Could not write __env.js to any known location');
  }

  return config;
}

/**
 * Patch CSP headers in routes-manifest.json with runtime environment values.
 *
 * Next.js bakes CSP headers into routes-manifest.json at build time. This
 * function rewrites frame-src and connect-src directives at container startup
 * so a single Docker image works across environments.
 */
function patchCspHeaders() {
  const possibleManifestPaths = [
    path.join(process.cwd(), '.next', 'routes-manifest.json'),
    path.join(process.cwd(), '..', '..', '.next', 'routes-manifest.json'),
  ];

  const frameSrc = process.env.NEXT_PUBLIC_CSP_FRAME_SRC;
  const apiUrl = process.env.NEXT_PUBLIC_API_URL;

  if (!frameSrc && !apiUrl) {
    console.log('[csp-patch] No CSP runtime env vars set — skipping');
    return;
  }

  let manifestPath = null;
  for (const p of possibleManifestPaths) {
    if (fs.existsSync(p)) {
      manifestPath = p;
      break;
    }
  }

  if (!manifestPath) {
    console.warn('[csp-patch] Warning: Could not find routes-manifest.json');
    return;
  }

  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch (err) {
    console.warn('[csp-patch] Warning: Could not parse routes-manifest.json:', err.message);
    return;
  }

  const headerRoutes = manifest.headers || [];
  let patched = false;

  for (const route of headerRoutes) {
    if (!route.headers) continue;

    for (const header of route.headers) {
      if (header.key !== 'Content-Security-Policy') continue;

      // Parse CSP string into a directive map
      const directives = new Map();
      for (const part of header.value.split('; ')) {
        const spaceIdx = part.indexOf(' ');
        if (spaceIdx === -1) {
          directives.set(part, '');
        } else {
          directives.set(part.substring(0, spaceIdx), part.substring(spaceIdx + 1));
        }
      }

      // Patch frame-src
      if (frameSrc) {
        const newFrameSrc = `'self' ${frameSrc} https:`;
        directives.set('frame-src', newFrameSrc);
        console.log(`[csp-patch] frame-src → ${newFrameSrc}`);
        patched = true;
      }

      // Patch connect-src
      if (apiUrl) {
        try {
          const apiOrigin = new URL(apiUrl).origin;
          const wsOrigin = apiOrigin.replace(/^http/, 'ws');
          const parts = ["'self'", apiOrigin, wsOrigin];

          const kcUrl = process.env.NEXT_PUBLIC_KEYCLOAK_URL;
          if (kcUrl) {
            try {
              parts.push(new URL(kcUrl).origin);
            } catch {
              // ignore invalid keycloak URL
            }
          }

          parts.push('https:', 'wss:');
          const newConnectSrc = parts.join(' ');
          directives.set('connect-src', newConnectSrc);
          console.log(`[csp-patch] connect-src → ${newConnectSrc}`);
          patched = true;
        } catch {
          console.warn(`[csp-patch] Warning: Could not parse NEXT_PUBLIC_API_URL: ${apiUrl}`);
        }
      }

      // Reassemble CSP string
      const cspParts = [];
      for (const [directive, value] of directives) {
        cspParts.push(value ? `${directive} ${value}` : directive);
      }
      header.value = cspParts.join('; ');
    }
  }

  if (patched) {
    try {
      fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
      console.log(`[csp-patch] Updated ${manifestPath}`);
    } catch (err) {
      console.warn('[csp-patch] Warning: Could not write routes-manifest.json:', err.message);
    }
  }
}

/**
 * Start the Next.js server
 */
function startNextServer() {
  // Try workspace-level node_modules first, then root-level
  const candidates = [
    path.join(process.cwd(), 'node_modules', 'next', 'dist', 'bin', 'next'),
    path.join(process.cwd(), '..', '..', 'node_modules', 'next', 'dist', 'bin', 'next'),
  ];

  const nextPath = candidates.find((p) => fs.existsSync(p));
  if (!nextPath) {
    console.error('[start-server] Could not find next binary. Searched:', candidates);
    process.exit(1);
  }

  console.log(`[start-server] Starting Next.js server...`);
  console.log(`[start-server] PORT=${process.env.PORT || 3000}`);
  console.log(`[start-server] NODE_ENV=${process.env.NODE_ENV || 'production'}`);

  // Start Next.js
  const nextProcess = spawn(process.execPath, [nextPath, 'start'], {
    stdio: 'inherit',
    env: {
      ...process.env,
      PORT: process.env.PORT || '3000',
      HOSTNAME: process.env.HOSTNAME || '0.0.0.0',
    },
  });

  nextProcess.on('error', (err) => {
    console.error('[start-server] Failed to start Next.js:', err);
    process.exit(1);
  });

  nextProcess.on('exit', (code) => {
    console.log(`[start-server] Next.js exited with code ${code}`);
    process.exit(code || 0);
  });

  // Forward signals
  process.on('SIGTERM', () => {
    console.log('[start-server] Received SIGTERM, shutting down...');
    nextProcess.kill('SIGTERM');
  });

  process.on('SIGINT', () => {
    console.log('[start-server] Received SIGINT, shutting down...');
    nextProcess.kill('SIGINT');
  });
}

// Main
console.log('[start-server] Perfana Web Container Startup');
console.log('[start-server] ================================');

const config = generateEnvFile();

if (Object.keys(config).length === 0) {
  console.log('[start-server] No runtime environment variables configured');
  console.log('[start-server] The app will use built-in defaults');
}

patchCspHeaders();
startNextServer();
