#!/bin/bash

# ================================================================================================
# PERFANA KEYCLOAK SETUP SCRIPT
# ================================================================================================
# This script sets up the Keycloak infrastructure for Phase 6 authentication migration
# Usage: ./keycloak/scripts/setup-keycloak.sh [start|stop|restart|status|logs]
# ================================================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." &> /dev/null && pwd)"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.keycloak.yml"
ENV_FILE="$PROJECT_ROOT/.env.keycloak"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed or not in PATH"
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is not installed or not in PATH"
        exit 1
    fi
}

create_env_file() {
    if [ ! -f "$ENV_FILE" ]; then
        log_info "Creating Keycloak environment file..."
        cat > "$ENV_FILE" << EOF
# ================================================================================================
# KEYCLOAK ENVIRONMENT CONFIGURATION
# ================================================================================================
# Generated by setup-keycloak.sh - Modify as needed for your environment
# ================================================================================================

# Database Configuration
KEYCLOAK_DB_PASSWORD=keycloak_dev_password_$(openssl rand -hex 8)

# Keycloak Admin Configuration
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin_dev_password_$(openssl rand -hex 8)

# Keycloak Server Configuration
KEYCLOAK_HOSTNAME=localhost
KEYCLOAK_PORT=8080

# Client Secrets (Change in production)
KEYCLOAK_API_CLIENT_SECRET=perfana-api-secret-$(openssl rand -hex 16)

# Development Settings
KEYCLOAK_DEV_MODE=true
KEYCLOAK_IMPORT_REALM=true
EOF
        log_success "Environment file created at $ENV_FILE"
        log_warning "Please review and update the environment variables as needed"
    else
        log_info "Environment file already exists at $ENV_FILE"
    fi
}

setup_networks() {
    log_info "Setting up Docker networks..."

    # Create the main development network if it doesn't exist
    if ! docker network ls | grep -q "perfana-dev"; then
        docker network create perfana-dev --driver bridge --subnet 172.25.0.0/24
        log_success "Created perfana-dev network"
    else
        log_info "perfana-dev network already exists"
    fi
}

start_keycloak() {
    log_info "Starting Keycloak infrastructure..."

    cd "$PROJECT_ROOT"
    docker-compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

    log_info "Waiting for Keycloak to be ready..."
    timeout=300
    elapsed=0

    while [ $elapsed -lt $timeout ]; do
        if curl -s -f http://localhost:8080/health/ready &> /dev/null; then
            log_success "Keycloak is ready!"
            break
        fi
        sleep 5
        elapsed=$((elapsed + 5))
        echo -n "."
    done

    if [ $elapsed -ge $timeout ]; then
        log_error "Keycloak failed to start within $timeout seconds"
        return 1
    fi

    log_success "Keycloak infrastructure started successfully"
    log_info "Keycloak Admin Console: http://localhost:8080"
    log_info "Default admin credentials are in $ENV_FILE"
}

stop_keycloak() {
    log_info "Stopping Keycloak infrastructure..."
    cd "$PROJECT_ROOT"
    docker-compose -f "$COMPOSE_FILE" down
    log_success "Keycloak infrastructure stopped"
}

restart_keycloak() {
    log_info "Restarting Keycloak infrastructure..."
    stop_keycloak
    sleep 2
    start_keycloak
}

show_status() {
    log_info "Keycloak infrastructure status:"
    cd "$PROJECT_ROOT"
    docker-compose -f "$COMPOSE_FILE" ps

    echo ""
    if curl -s -f http://localhost:8080/health/ready &> /dev/null; then
        log_success "Keycloak is healthy and ready"
        log_info "Admin Console: http://localhost:8080"
        log_info "Realm endpoint: http://localhost:8080/realms/perfana-prod"
        log_info "JWKS endpoint: http://localhost:8080/realms/perfana-prod/protocol/openid-connect/certs"
    else
        log_warning "Keycloak is not responding or not ready"
    fi
}

show_logs() {
    log_info "Showing Keycloak logs..."
    cd "$PROJECT_ROOT"
    docker-compose -f "$COMPOSE_FILE" logs -f
}

show_help() {
    echo "Perfana Keycloak Setup Script"
    echo ""
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  start     Start Keycloak infrastructure"
    echo "  stop      Stop Keycloak infrastructure"
    echo "  restart   Restart Keycloak infrastructure"
    echo "  status    Show status of Keycloak services"
    echo "  logs      Show and follow Keycloak logs"
    echo "  help      Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 start          # Start Keycloak"
    echo "  $0 status         # Check if services are running"
    echo "  $0 logs           # View logs"
    echo ""
}

# Main execution
main() {
    check_docker
    create_env_file
    setup_networks

    case "${1:-start}" in
        start)
            start_keycloak
            ;;
        stop)
            stop_keycloak
            ;;
        restart)
            restart_keycloak
            ;;
        status)
            show_status
            ;;
        logs)
            show_logs
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            log_error "Unknown command: $1"
            show_help
            exit 1
            ;;
    esac
}

# Execute main function with all arguments
main "$@"