/**
 * Runtime Configuration for Next.js
 *
 * This module handles runtime environment variables for containerized deployments.
 * Since Next.js inlines NEXT_PUBLIC_* variables at build time, we need a mechanism
 * to override these values at runtime for different environments.
 *
 * Strategy:
 * 1. Build with placeholder values (e.g., __RUNTIME_NEXT_PUBLIC_API_URL__)
 * 2. At runtime, fetch config from /api/config which reads actual env vars
 * 3. Store config in window.__ENV__ for client-side access
 * 4. The app reads from window.__ENV__ with fallback to build-time values
 */

// Environment variable keys that can be configured at runtime
export const RUNTIME_ENV_KEYS = [
  'NEXT_PUBLIC_API_URL',
  'NEXT_PUBLIC_KEYCLOAK_URL',
  'NEXT_PUBLIC_KEYCLOAK_REALM',
  'NEXT_PUBLIC_KEYCLOAK_CLIENT_ID',
  'NEXT_PUBLIC_USE_KEYCLOAK_AUTH',
  'NEXT_PUBLIC_LOG_VIEWER_ENABLED',
  'NEXT_PUBLIC_SUT_TRANSFER_ENABLED',
] as const;

export type RuntimeEnvKey = (typeof RUNTIME_ENV_KEYS)[number];

// Placeholder prefix used during build
export const PLACEHOLDER_PREFIX = '__RUNTIME_';
export const PLACEHOLDER_SUFFIX = '__';

// Flag to track if config has been loaded
let configLoaded = false;
let configLoadPromise: Promise<void> | null = null;

/**
 * Check if a value is a placeholder (not replaced at runtime)
 */
export function isPlaceholder(value: string | undefined): boolean {
  if (!value) return false;
  return value.startsWith(PLACEHOLDER_PREFIX) && value.endsWith(PLACEHOLDER_SUFFIX);
}

/**
 * Load runtime configuration from the server API
 * This fetches /api/config which reads env vars at request time
 */
export async function loadRuntimeConfig(): Promise<void> {
  if (configLoaded) return;
  if (configLoadPromise) return configLoadPromise;

  configLoadPromise = (async () => {
    try {
      // Only fetch on client side
      if (typeof window === 'undefined') return;

      const response = await fetch('/api/config');
      if (response.ok) {
        const config = await response.json();
        (window as Window & { __ENV__?: Record<string, string> }).__ENV__ = config;
        console.log('[runtime-config] Loaded config from /api/config:', Object.keys(config));
      } else {
        console.warn('[runtime-config] Failed to fetch /api/config:', response.status);
      }
    } catch (error) {
      console.warn('[runtime-config] Error fetching config:', error);
    } finally {
      configLoaded = true;
    }
  })();

  return configLoadPromise;
}

/**
 * Get runtime environment variable value
 * Priority: window.__ENV__ > process.env > default value
 */
export function getRuntimeEnv(key: RuntimeEnvKey, defaultValue?: string): string | undefined {
  // Client-side: check window.__ENV__ first (populated by loadRuntimeConfig or __env.js)
  if (typeof window !== 'undefined') {
    const windowEnv = (window as Window & { __ENV__?: Record<string, string> }).__ENV__;
    if (windowEnv && windowEnv[key] && !isPlaceholder(windowEnv[key])) {
      return windowEnv[key];
    }
  }

  // Check process.env (works during SSR and when not using placeholders)
  const envValue = process.env[key];
  if (envValue && !isPlaceholder(envValue)) {
    return envValue;
  }

  return defaultValue;
}

/**
 * Generate the __env.js script content for runtime configuration
 * This is called at container startup to create the config file
 */
export function generateEnvScript(env: Record<string, string | undefined>): string {
  const config: Record<string, string> = {};

  for (const key of RUNTIME_ENV_KEYS) {
    const value = env[key];
    if (value && !isPlaceholder(value)) {
      config[key] = value;
    }
  }

  return `// Runtime environment configuration - Generated at container startup
// Do not edit this file manually
window.__ENV__ = ${JSON.stringify(config, null, 2)};
`;
}
