import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { GeneratedReport, ReportStatus } from '@perfana/shared/entities';
import { BrowserPoolService } from './browser-pool.service';

/**
 * PDF options for Puppeteer
 */
interface PdfOptions {
  format: 'A4' | 'Letter';
  printBackground: boolean;
  margin: {
    top: string;
    right: string;
    bottom: string;
    left: string;
  };
  displayHeaderFooter: boolean;
  headerTemplate: string;
  footerTemplate: string;
}

/**
 * PDF Service
 *
 * Handles PDF generation from HTML content using Puppeteer.
 * Uses the browser pool for efficient resource management.
 */
@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private readonly pdfTimeout: number;

  constructor(
    private readonly configService: ConfigService,
    private readonly browserPoolService: BrowserPoolService,
    @InjectRepository(GeneratedReport)
    private readonly reportRepo: Repository<GeneratedReport>
  ) {
    this.pdfTimeout = this.configService.get<number>('PDF_TIMEOUT_MS', 90000);
  }

  /**
   * Generate PDF from report ID
   *
   * @param reportId - UUID of the report to generate PDF for
   * @returns PDF buffer
   */
  async generatePdf(reportId: string): Promise<Buffer> {
    this.logger.log(`Starting PDF generation for report ${reportId}`);

    // Get the report with HTML content
    const report = await this.reportRepo.findOne({
      where: { id: reportId },
    });

    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (!report.html_content) {
      throw new Error(
        `Report ${reportId} does not have HTML content. Generate HTML first.`
      );
    }

    // Generate PDF from HTML
    const result = await this.generatePdfFromHtml(
      report.html_content,
      report.name
    );

    // Populate file_metadata with page count and Puppeteer version
    const fileMetadata: Record<string, unknown> = {};
    if (result.pageCount != null) fileMetadata.pageCount = result.pageCount;
    if (result.puppeteerVersion != null)
      fileMetadata.puppeteerVersion = result.puppeteerVersion;

    if (Object.keys(fileMetadata).length > 0) {
      await this.reportRepo.update(reportId, {
        file_metadata: fileMetadata as any,
      });
      this.logger.log(
        `Updated file_metadata for report ${reportId}: ${JSON.stringify(fileMetadata)}`
      );
    }

    this.logger.log(
      `PDF generated successfully for report ${reportId}, size: ${this.formatFileSize(result.buffer.length)}`
    );

    return result.buffer;
  }

  /**
   * Generate PDF from HTML content using Puppeteer
   */
  private async generatePdfFromHtml(
    htmlContent: string,
    reportName: string
  ): Promise<{
    buffer: Buffer;
    pageCount: number | null;
    puppeteerVersion: string | null;
  }> {
    let page = null;

    try {
      this.logger.debug('Getting browser from pool for PDF generation...');

      // Get browser from pool
      const browser = await this.browserPoolService.getBrowser();

      this.logger.debug('Browser obtained from pool successfully');

      page = await browser.newPage();

      // Set content with proper base URL for relative resources
      this.logger.debug('Setting page content for PDF generation...');
      await page.setContent(htmlContent, {
        waitUntil: ['domcontentloaded', 'networkidle0'],
        timeout: 60000, // 60 second timeout for content loading
      });

      this.logger.debug('Page content loaded, generating PDF...');

      // Configure PDF options
      const pdfOptions: PdfOptions = {
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20mm',
          right: '15mm',
          bottom: '20mm',
          left: '15mm',
        },
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size: 9px; text-align: center; width: 100%; color: #666;">
            ${this.escapeHtml(reportName)}
          </div>
        `,
        footerTemplate: `
          <div style="font-size: 9px; text-align: center; width: 100%; color: #666;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span> | Generated by Perfana
          </div>
        `,
      };

      // Generate PDF with timeout
      const pdfBuffer = await Promise.race([
        page.pdf(pdfOptions),
        new Promise<never>((_, reject) =>
          setTimeout(
            () => reject(new Error('PDF generation timeout')),
            this.pdfTimeout
          )
        ),
      ]);

      // Get page count from Puppeteer metrics
      const pageCount = await page
        .evaluate(() => {
          // CSS page-break elements define page boundaries; approximate via content height / A4 height
          const body = document.body;
          const totalHeight = Math.max(body.scrollHeight, body.offsetHeight);
          const a4HeightPx = 1123; // A4 at 96 DPI minus margins (~297mm - 40mm margins)
          return Math.max(1, Math.ceil(totalHeight / a4HeightPx));
        })
        .catch(() => null);

      const browserVersion = await page
        .browser()
        .version()
        .catch(() => null);

      this.logger.debug(
        `PDF generated successfully, size: ${pdfBuffer.length} bytes, ~${pageCount} pages`
      );

      return {
        buffer: Buffer.from(pdfBuffer),
        pageCount,
        puppeteerVersion: browserVersion,
      };
    } finally {
      // Clean up page (but keep browser in pool)
      if (page) {
        await page.close().catch(error => {
          const errorMessage =
            error && typeof error === 'object' && 'message' in error
              ? (error as Error).message
              : 'Unknown error';
          this.logger.warn(`Error closing page: ${errorMessage}`);
        });
      }
    }
  }

  /**
   * Update report status in database
   */
  async updateReportStatus(
    reportId: string,
    status: ReportStatus,
    errorMessage?: string,
    errorCode?: string
  ): Promise<void> {
    const updateData: Partial<GeneratedReport> = { status };

    if (status === 'failed') {
      updateData.error_message = errorMessage;
      updateData.error_code = errorCode;
      updateData.completed_at = new Date();
    }

    if (status === 'pdf_complete') {
      updateData.completed_at = new Date();
    }

    if (status === 'pdf_processing') {
      updateData.started_at = new Date();
    }

    await this.reportRepo.update(reportId, updateData as any);
  }

  /**
   * Store PDF data and metadata in database
   */
  async storePdfMetadata(reportId: string, pdfBuffer: Buffer): Promise<void> {
    try {
      // Store PDF binary data directly in database
      await this.reportRepo.update(reportId, {
        pdf_data: pdfBuffer,
        file_size: pdfBuffer.length,
        mime_type: 'application/pdf',
        status: 'pdf_complete' as ReportStatus,
        completed_at: new Date(),
      });

      this.logger.log(
        `Stored PDF data in database for report ${reportId} (${this.formatFileSize(pdfBuffer.length)})`
      );
    } catch (error) {
      const errorMessage =
        error && typeof error === 'object' && 'message' in error
          ? (error as Error).message
          : 'Unknown error';
      this.logger.error(`Failed to store PDF data: ${errorMessage}`);
      throw new Error(`Failed to store PDF data: ${errorMessage}`);
    }
  }

  /**
   * Format file size for logging
   */
  private formatFileSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  }

  /**
   * Escape HTML special characters
   */
  private escapeHtml(text: string): string {
    if (!text) return '';
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, char => map[char] || char);
  }
}
