import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Restores the two functional unique indexes that AddWorkloadToEvents
 * (1776148518354) silently dropped — the migration was auto-generated by
 * TypeORM, which doesn't recognize expression-based indexes, so both were
 * removed without a replacement.
 *
 * 1. test_run_configs_test_run_id_key_tags_key on
 *    (test_run_id, key, tags_hash(tags)). Added by AddTagsHashUniqueIndex
 *    (1700000000003) so the same key can coexist with different tag sets.
 *    Its absence breaks every INSERT … ON CONFLICT (test_run_id, key,
 *    tags_hash(tags)) upsert in TestRunsConfigService — including the JTL
 *    upload flow (SQLSTATE 42P10).
 *
 * 2. idx_dynatrace_entity_mappings_unique on (system_under_test_id,
 *    COALESCE(test_environment,''), COALESCE(workload,''), entity_id).
 *    Original schema constraint preventing duplicate dynatrace entity
 *    mappings per SUT/env/workload. No live ON CONFLICT depends on it
 *    today, but losing it removes the data-integrity guarantee.
 *
 * All blocks are idempotent (CREATE OR REPLACE / IF NOT EXISTS) so the
 * migration is safe on databases at any state.
 */
export class RestoreTestRunConfigsTagsHashUniqueIndex1776900000000
  implements MigrationInterface
{
  name = 'RestoreTestRunConfigsTagsHashUniqueIndex1776900000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION tags_hash(tags text[])
      RETURNS text
      LANGUAGE sql
      IMMUTABLE
      AS $$
        SELECT md5(COALESCE(array_to_string(tags, ','), ''))
      $$;
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS test_run_configs_test_run_id_key_tags_key
        ON test_run_configs (test_run_id, key, tags_hash(tags));
    `);

    const dupCheck = await queryRunner.query(`
      SELECT COUNT(*)::int AS dup_count
      FROM (
        SELECT 1
        FROM dynatrace_entity_mappings
        GROUP BY system_under_test_id,
                 COALESCE(test_environment, ''),
                 COALESCE(workload, ''),
                 entity_id
        HAVING COUNT(*) > 1
      ) t
    `);
    if (dupCheck[0]?.dup_count > 0) {
      throw new Error(
        `Cannot create idx_dynatrace_entity_mappings_unique: ${dupCheck[0].dup_count} duplicate ` +
          `(system_under_test_id, COALESCE(test_environment,''), COALESCE(workload,''), entity_id) ` +
          `groups exist in dynatrace_entity_mappings. Dedupe before re-running.`,
      );
    }
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_dynatrace_entity_mappings_unique
        ON dynatrace_entity_mappings (
          system_under_test_id,
          COALESCE(test_environment, ''::character varying),
          COALESCE(workload, ''::character varying),
          entity_id
        );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS idx_dynatrace_entity_mappings_unique`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS test_run_configs_test_run_id_key_tags_key`,
    );
  }
}
