import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProxyServer1783409734007 implements MigrationInterface {
    name = 'AddProxyServer1783409734007'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP CONSTRAINT "fk_workload_transaction_apdex_thresholds_system_under_test"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP CONSTRAINT "fk_workload_apdex_thresholds_system_under_test"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_trans_apdex_environment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_trans_apdex_system"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_trans_apdex_transaction"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_trans_apdex_workload"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_transaction_apdex_thresholds_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_transaction_apdex_thresholds_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_transaction_apdex_thresholds_team_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_environment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_system"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_thresholds_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_thresholds_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_thresholds_team_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_workload_apdex_workload"`);
        await queryRunner.query(`DROP INDEX "public"."test_run_configs_test_run_id_key_tags_key"`);
        await queryRunner.query(`DROP INDEX "public"."uq_system_under_test_name_org"`);
        await queryRunner.query(`DROP INDEX "public"."idx_dynatrace_entity_mappings_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ds_metrics_panel_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_metrics_upsert"`);
        await queryRunner.query(`DROP INDEX "public"."ds_metrics_time_idx"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_metric_statistics"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_control_groups_cgid"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_control_group_statistics"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_compare_config_metric"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_compare_config_panel"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_adapt_tracked_results"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_adapt_results"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_ds_adapt_conclusion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_resource"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_system_under_test_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."api_keys_organization_id_description_key"`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP CONSTRAINT "workload_transaction_apdex_thresholds_apdex_threshold_check"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP CONSTRAINT "workload_apdex_thresholds_apdex_threshold_check"`);
        await queryRunner.query(`ALTER TABLE "system_under_test_test_environments" DROP CONSTRAINT "system_under_test_test_environments_system_under_test_id_name_k"`);
        await queryRunner.query(`ALTER TABLE "system_under_test_workloads" DROP CONSTRAINT "application_test_types_application_test_environment_id_name_key"`);
        await queryRunner.query(`CREATE TABLE "proxy_servers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "proxy_url" text NOT NULL, "username" text, "password" text, "team_id" uuid, "created_by" character varying(255), "updated_by" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_proxy_servers_organization" UNIQUE ("organization_id"), CONSTRAINT "PK_8708f2b15e69d2466115a372443" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" DROP COLUMN "pct_agg"`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" DROP COLUMN "sum_value"`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" DROP COLUMN "sum_sq_value"`);
        await queryRunner.query(`ALTER TABLE "pyroscope_instances" ADD "use_proxy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "grafana_instances" ADD "use_proxy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tracing_instances" ADD "use_proxy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "notification_channels" ADD "use_proxy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "dynatrace_configs" ADD "use_proxy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ALTER COLUMN "apdex_threshold" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "organizations_name_key"`);
        await queryRunner.query(`ALTER TABLE "test_runs" ALTER COLUMN "ramp_down" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "test_runs" ALTER COLUMN "organization_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "benchmarks" DROP COLUMN "dashboard_id"`);
        await queryRunner.query(`ALTER TABLE "benchmarks" ADD "dashboard_id" integer`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_system_under_test_id" ON "audit_logs" ("system_under_test_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_organization_id" ON "audit_logs" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("user_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_resource"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_system_under_test_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "timestamp" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id", "timestamp")`);
        await queryRunner.query(`ALTER TABLE "benchmarks" DROP COLUMN "dashboard_id"`);
        await queryRunner.query(`ALTER TABLE "benchmarks" ADD "dashboard_id" bigint`);
        await queryRunner.query(`ALTER TABLE "test_runs" ALTER COLUMN "organization_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_runs" ALTER COLUMN "ramp_down" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "organizations_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ALTER COLUMN "apdex_threshold" SET DEFAULT '500'`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dynatrace_configs" DROP COLUMN "use_proxy"`);
        await queryRunner.query(`ALTER TABLE "notification_channels" DROP COLUMN "use_proxy"`);
        await queryRunner.query(`ALTER TABLE "tracing_instances" DROP COLUMN "use_proxy"`);
        await queryRunner.query(`ALTER TABLE "grafana_instances" DROP COLUMN "use_proxy"`);
        await queryRunner.query(`ALTER TABLE "pyroscope_instances" DROP COLUMN "use_proxy"`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" ADD "sum_sq_value" double precision`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" ADD "sum_value" double precision`);
        await queryRunner.query(`ALTER TABLE "ds_metric_statistics" ADD "pct_agg" uddsketch`);
        await queryRunner.query(`DROP TABLE "proxy_servers"`);
        await queryRunner.query(`ALTER TABLE "system_under_test_workloads" ADD CONSTRAINT "application_test_types_application_test_environment_id_name_key" UNIQUE ("system_under_test_test_environment_id", "name")`);
        await queryRunner.query(`ALTER TABLE "system_under_test_test_environments" ADD CONSTRAINT "system_under_test_test_environments_system_under_test_id_name_k" UNIQUE ("system_under_test_id", "name")`);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD CONSTRAINT "workload_apdex_thresholds_apdex_threshold_check" CHECK (((apdex_threshold > 0) AND (apdex_threshold <= 60000)))`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD CONSTRAINT "workload_transaction_apdex_thresholds_apdex_threshold_check" CHECK (((apdex_threshold > 0) AND (apdex_threshold <= 60000)))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "api_keys_organization_id_description_key" ON "api_keys" ("description", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("timestamp", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_system_under_test_id" ON "audit_logs" ("timestamp", "system_under_test_id") WHERE (system_under_test_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" ("timestamp", "resource_type", "resource_id") WHERE (resource_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_organization_id" ON "audit_logs" ("timestamp", "organization_id") WHERE (organization_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "audit_logs" ("timestamp", "action") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_adapt_conclusion" ON "ds_adapt_conclusion" ("test_run_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_adapt_results" ON "ds_adapt_results" ("test_run_id", "control_group_id", "application_dashboard_id", "panel_id", "metric_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_adapt_tracked_results" ON "ds_adapt_tracked_results" ("test_run_id", "tracked_test_run_id", "application_dashboard_id", "panel_id", "metric_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_compare_config_panel" ON "ds_compare_config" ("application_dashboard_id", "panel_id", "system_under_test_id", "test_environment", "workload") WHERE (metric_name IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_compare_config_metric" ON "ds_compare_config" ("application_dashboard_id", "panel_id", "metric_name", "system_under_test_id", "test_environment", "workload") WHERE (metric_name IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_control_group_statistics" ON "ds_control_group_statistics" ("control_group_id", "application_dashboard_id", "panel_id", "metric_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_control_groups_cgid" ON "ds_control_groups" ("control_group_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_metric_statistics" ON "ds_metric_statistics" ("test_run_id", "application_dashboard_id", "panel_id", "metric_name") `);
        await queryRunner.query(`CREATE INDEX "ds_metrics_time_idx" ON "ds_metrics" ("time") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_ds_metrics_upsert" ON "ds_metrics" ("test_run_id", "application_dashboard_id", "panel_id", "time", "metric_name") `);
        await queryRunner.query(`CREATE INDEX "idx_ds_metrics_panel_lookup" ON "ds_metrics" ("test_run_id", "panel_id", "metric_name", "panel_title", "dashboard_label", "unit") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_dynatrace_entity_mappings_unique" ON "dynatrace_entity_mappings" ("system_under_test_id", "entity_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_system_under_test_name_org" ON "systems_under_test" ("name", "organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "test_run_configs_test_run_id_key_tags_key" ON "test_run_configs" ("test_run_id", "key") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_workload" ON "workload_apdex_thresholds" ("workload") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_thresholds_team_id" ON "workload_apdex_thresholds" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_thresholds_organization_id" ON "workload_apdex_thresholds" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_thresholds_created_by" ON "workload_apdex_thresholds" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_system" ON "workload_apdex_thresholds" ("system_under_test_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_apdex_environment" ON "workload_apdex_thresholds" ("test_environment") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_transaction_apdex_thresholds_team_id" ON "workload_transaction_apdex_thresholds" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_transaction_apdex_thresholds_organization_id" ON "workload_transaction_apdex_thresholds" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_transaction_apdex_thresholds_created_by" ON "workload_transaction_apdex_thresholds" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_trans_apdex_workload" ON "workload_transaction_apdex_thresholds" ("workload") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_trans_apdex_transaction" ON "workload_transaction_apdex_thresholds" ("transaction_name") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_trans_apdex_system" ON "workload_transaction_apdex_thresholds" ("system_under_test_id") `);
        await queryRunner.query(`CREATE INDEX "idx_workload_trans_apdex_environment" ON "workload_transaction_apdex_thresholds" ("test_environment") `);
        await queryRunner.query(`ALTER TABLE "workload_apdex_thresholds" ADD CONSTRAINT "fk_workload_apdex_thresholds_system_under_test" FOREIGN KEY ("system_under_test_id") REFERENCES "systems_under_test"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workload_transaction_apdex_thresholds" ADD CONSTRAINT "fk_workload_transaction_apdex_thresholds_system_under_test" FOREIGN KEY ("system_under_test_id") REFERENCES "systems_under_test"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
